//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.15 at 10:43:38 AM CET 
//


package org.isima.carsharing.elements.utilities;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class GraphBuilder {

    private final static QName _SimulationLocationsLocationPositionY_QNAME = new QName("", "y");
    private final static QName _SimulationLocationsLocationPositionX_QNAME = new QName("", "x");
    private final static QName _SimulationRequestsRequestCarsNumber_QNAME = new QName("", "carsNumber");
    private final static QName _SimulationRequestsRequestTo_QNAME = new QName("", "to");
    private final static QName _SimulationRequestsRequestValid_QNAME = new QName("", "valid");
    private final static QName _SimulationRequestsRequestDropTime_QNAME = new QName("", "dropTime");
    private final static QName _SimulationRequestsRequestDelayed_QNAME = new QName("", "delayed");
    private final static QName _SimulationRequestsRequestAskTime_QNAME = new QName("", "askTime");
    private final static QName _SimulationRequestsRequestDeadlineTime_QNAME = new QName("", "deadlineTime");
    private final static QName _SimulationRequestsRequestPickupTime_QNAME = new QName("", "pickupTime");
    private final static QName _SimulationRequestsRequestRelatedRequest_QNAME = new QName("", "relatedRequest");
    private final static QName _SimulationRequestsRequestFrom_QNAME = new QName("", "from");
    private final static QName _SimulationRequestsRequestType_QNAME = new QName("", "type");
    private final static QName _SimulationRequestsRequestId_QNAME = new QName("", "id");
    private final static QName _SimulationRequestsRequestOptimized_QNAME = new QName("", "optimized");
    private final static QName _SimulationLocationsLocationPosition_QNAME = new QName("", "position");
    private final static QName _SimulationLocationsLocationDriverAvailable_QNAME = new QName("", "driverAvailable");
    private final static QName _SimulationLocationsLocationParkedCar_QNAME = new QName("", "parkedCar");
    private final static QName _SimulationLocationsLocationCapacity_QNAME = new QName("", "capacity");
    private final static QName _SimulationDistancesDistanceDist_QNAME = new QName("", "dist");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public GraphBuilder() {
    }

    /**
     * Create an instance of {@link Simulation }
     * 
     */
    public Simulation createSimulation() {
        return new Simulation();
    }

    /**
     * Create an instance of {@link Simulation.Requests }
     * 
     */
    public Simulation.Requests createSimulationRequests() {
        return new Simulation.Requests();
    }

    /**
     * Create an instance of {@link Simulation.Requests.Request }
     * 
     */
    public Simulation.Requests.Request createSimulationRequestsRequest() {
        return new Simulation.Requests.Request();
    }

    /**
     * Create an instance of {@link Simulation.Locations }
     * 
     */
    public Simulation.Locations createSimulationLocations() {
        return new Simulation.Locations();
    }

    /**
     * Create an instance of {@link Simulation.Locations.Location }
     * 
     */
    public Simulation.Locations.Location createSimulationLocationsLocation() {
        return new Simulation.Locations.Location();
    }

    /**
     * Create an instance of {@link Simulation.Distances }
     * 
     */
    public Simulation.Distances createSimulationDistances() {
        return new Simulation.Distances();
    }

    /**
     * Create an instance of {@link Simulation.Requests.Request.RelatedRequest }
     * 
     */
    public Simulation.Requests.Request.RelatedRequest createSimulationRequestsRequestRelatedRequest() {
        return new Simulation.Requests.Request.RelatedRequest();
    }

    /**
     * Create an instance of {@link Simulation.Locations.Location.Position }
     * 
     */
    public Simulation.Locations.Location.Position createSimulationLocationsLocationPosition() {
        return new Simulation.Locations.Location.Position();
    }

    /**
     * Create an instance of {@link Simulation.Distances.Distance }
     * 
     */
    public Simulation.Distances.Distance createSimulationDistancesDistance() {
        return new Simulation.Distances.Distance();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "y", scope = Simulation.Locations.Location.Position.class)
    public JAXBElement<BigInteger> createSimulationLocationsLocationPositionY(BigInteger value) {
        return new JAXBElement<BigInteger>(_SimulationLocationsLocationPositionY_QNAME, BigInteger.class, Simulation.Locations.Location.Position.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "x", scope = Simulation.Locations.Location.Position.class)
    public JAXBElement<BigInteger> createSimulationLocationsLocationPositionX(BigInteger value) {
        return new JAXBElement<BigInteger>(_SimulationLocationsLocationPositionX_QNAME, BigInteger.class, Simulation.Locations.Location.Position.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "carsNumber", scope = Simulation.Requests.Request.class)
    public JAXBElement<String> createSimulationRequestsRequestCarsNumber(String value) {
        return new JAXBElement<String>(_SimulationRequestsRequestCarsNumber_QNAME, String.class, Simulation.Requests.Request.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "to", scope = Simulation.Requests.Request.class)
    public JAXBElement<String> createSimulationRequestsRequestTo(String value) {
        return new JAXBElement<String>(_SimulationRequestsRequestTo_QNAME, String.class, Simulation.Requests.Request.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "valid", scope = Simulation.Requests.Request.class)
    public JAXBElement<String> createSimulationRequestsRequestValid(String value) {
        return new JAXBElement<String>(_SimulationRequestsRequestValid_QNAME, String.class, Simulation.Requests.Request.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dropTime", scope = Simulation.Requests.Request.class)
    public JAXBElement<BigInteger> createSimulationRequestsRequestDropTime(BigInteger value) {
        return new JAXBElement<BigInteger>(_SimulationRequestsRequestDropTime_QNAME, BigInteger.class, Simulation.Requests.Request.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "delayed", scope = Simulation.Requests.Request.class)
    public JAXBElement<String> createSimulationRequestsRequestDelayed(String value) {
        return new JAXBElement<String>(_SimulationRequestsRequestDelayed_QNAME, String.class, Simulation.Requests.Request.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "askTime", scope = Simulation.Requests.Request.class)
    public JAXBElement<BigInteger> createSimulationRequestsRequestAskTime(BigInteger value) {
        return new JAXBElement<BigInteger>(_SimulationRequestsRequestAskTime_QNAME, BigInteger.class, Simulation.Requests.Request.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "deadlineTime", scope = Simulation.Requests.Request.class)
    public JAXBElement<BigInteger> createSimulationRequestsRequestDeadlineTime(BigInteger value) {
        return new JAXBElement<BigInteger>(_SimulationRequestsRequestDeadlineTime_QNAME, BigInteger.class, Simulation.Requests.Request.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pickupTime", scope = Simulation.Requests.Request.class)
    public JAXBElement<BigInteger> createSimulationRequestsRequestPickupTime(BigInteger value) {
        return new JAXBElement<BigInteger>(_SimulationRequestsRequestPickupTime_QNAME, BigInteger.class, Simulation.Requests.Request.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Simulation.Requests.Request.RelatedRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "relatedRequest", scope = Simulation.Requests.Request.class)
    public JAXBElement<Simulation.Requests.Request.RelatedRequest> createSimulationRequestsRequestRelatedRequest(Simulation.Requests.Request.RelatedRequest value) {
        return new JAXBElement<Simulation.Requests.Request.RelatedRequest>(_SimulationRequestsRequestRelatedRequest_QNAME, Simulation.Requests.Request.RelatedRequest.class, Simulation.Requests.Request.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "from", scope = Simulation.Requests.Request.class)
    public JAXBElement<String> createSimulationRequestsRequestFrom(String value) {
        return new JAXBElement<String>(_SimulationRequestsRequestFrom_QNAME, String.class, Simulation.Requests.Request.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "type", scope = Simulation.Requests.Request.class)
    public JAXBElement<String> createSimulationRequestsRequestType(String value) {
        return new JAXBElement<String>(_SimulationRequestsRequestType_QNAME, String.class, Simulation.Requests.Request.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "id", scope = Simulation.Requests.Request.class)
    public JAXBElement<BigInteger> createSimulationRequestsRequestId(BigInteger value) {
        return new JAXBElement<BigInteger>(_SimulationRequestsRequestId_QNAME, BigInteger.class, Simulation.Requests.Request.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "optimized", scope = Simulation.Requests.Request.class)
    public JAXBElement<String> createSimulationRequestsRequestOptimized(String value) {
        return new JAXBElement<String>(_SimulationRequestsRequestOptimized_QNAME, String.class, Simulation.Requests.Request.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Simulation.Locations.Location.Position }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "position", scope = Simulation.Locations.Location.class)
    public JAXBElement<Simulation.Locations.Location.Position> createSimulationLocationsLocationPosition(Simulation.Locations.Location.Position value) {
        return new JAXBElement<Simulation.Locations.Location.Position>(_SimulationLocationsLocationPosition_QNAME, Simulation.Locations.Location.Position.class, Simulation.Locations.Location.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "id", scope = Simulation.Locations.Location.class)
    public JAXBElement<String> createSimulationLocationsLocationId(String value) {
        return new JAXBElement<String>(_SimulationRequestsRequestId_QNAME, String.class, Simulation.Locations.Location.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "driverAvailable", scope = Simulation.Locations.Location.class)
    public JAXBElement<BigInteger> createSimulationLocationsLocationDriverAvailable(BigInteger value) {
        return new JAXBElement<BigInteger>(_SimulationLocationsLocationDriverAvailable_QNAME, BigInteger.class, Simulation.Locations.Location.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "parkedCar", scope = Simulation.Locations.Location.class)
    public JAXBElement<BigInteger> createSimulationLocationsLocationParkedCar(BigInteger value) {
        return new JAXBElement<BigInteger>(_SimulationLocationsLocationParkedCar_QNAME, BigInteger.class, Simulation.Locations.Location.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "capacity", scope = Simulation.Locations.Location.class)
    public JAXBElement<BigInteger> createSimulationLocationsLocationCapacity(BigInteger value) {
        return new JAXBElement<BigInteger>(_SimulationLocationsLocationCapacity_QNAME, BigInteger.class, Simulation.Locations.Location.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "type", scope = Simulation.Locations.Location.class)
    public JAXBElement<String> createSimulationLocationsLocationType(String value) {
        return new JAXBElement<String>(_SimulationRequestsRequestType_QNAME, String.class, Simulation.Locations.Location.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "id", scope = Simulation.Distances.Distance.class)
    public JAXBElement<BigInteger> createSimulationDistancesDistanceId(BigInteger value) {
        return new JAXBElement<BigInteger>(_SimulationRequestsRequestId_QNAME, BigInteger.class, Simulation.Distances.Distance.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "to", scope = Simulation.Distances.Distance.class)
    public JAXBElement<String> createSimulationDistancesDistanceTo(String value) {
        return new JAXBElement<String>(_SimulationRequestsRequestTo_QNAME, String.class, Simulation.Distances.Distance.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "from", scope = Simulation.Distances.Distance.class)
    public JAXBElement<String> createSimulationDistancesDistanceFrom(String value) {
        return new JAXBElement<String>(_SimulationRequestsRequestFrom_QNAME, String.class, Simulation.Distances.Distance.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dist", scope = Simulation.Distances.Distance.class)
    public JAXBElement<BigInteger> createSimulationDistancesDistanceDist(BigInteger value) {
        return new JAXBElement<BigInteger>(_SimulationDistancesDistanceDist_QNAME, BigInteger.class, Simulation.Distances.Distance.class, value);
    }

}
