//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.15 at 10:43:38 AM CET 
//

package org.isima.carsharing.elements.utilities;
import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="isLog" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="distances">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="distance" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                             &lt;element name="dist" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                             &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="to" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                           &lt;/choice>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="locations">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="location" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                             &lt;element name="parkedCar" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                             &lt;element name="capacity" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                             &lt;element name="driverAvailable" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                             &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="position">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                                       &lt;element name="x" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                                       &lt;element name="y" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                                     &lt;/choice>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/choice>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="requests">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="request" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                             &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                             &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="askTime" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                             &lt;element name="to" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="pickupTime" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                             &lt;element name="dropTime" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                             &lt;element name="deadlineTime" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                             &lt;element name="valid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="optimized" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="delayed" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="relatedRequest">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="requestId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="carsNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/choice>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "isLog",
    "distances",
    "locations",
    "requests"
})
@XmlRootElement(name = "simulation")
public class Simulation {

    @XmlElement(required = true)
    protected String isLog;
    @XmlElement(required = true)
    protected Simulation.Distances distances;
    @XmlElement(required = true)
    protected Simulation.Locations locations;
    @XmlElement(required = true)
    protected Simulation.Requests requests;

    /**
     * Gets the value of the isLog property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsLog() {
        return isLog;
    }

    /**
     * Sets the value of the isLog property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsLog(String value) {
        this.isLog = value;
    }

    /**
     * Gets the value of the distances property.
     * 
     * @return
     *     possible object is
     *     {@link Simulation.Distances }
     *     
     */
    public Simulation.Distances getDistances() {
        return distances;
    }

    /**
     * Sets the value of the distances property.
     * 
     * @param value
     *     allowed object is
     *     {@link Simulation.Distances }
     *     
     */
    public void setDistances(Simulation.Distances value) {
        this.distances = value;
    }

    /**
     * Gets the value of the locations property.
     * 
     * @return
     *     possible object is
     *     {@link Simulation.Locations }
     *     
     */
    public Simulation.Locations getLocations() {
        return locations;
    }

    /**
     * Sets the value of the locations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Simulation.Locations }
     *     
     */
    public void setLocations(Simulation.Locations value) {
        this.locations = value;
    }

    /**
     * Gets the value of the requests property.
     * 
     * @return
     *     possible object is
     *     {@link Simulation.Requests }
     *     
     */
    public Simulation.Requests getRequests() {
        return requests;
    }

    /**
     * Sets the value of the requests property.
     * 
     * @param value
     *     allowed object is
     *     {@link Simulation.Requests }
     *     
     */
    public void setRequests(Simulation.Requests value) {
        this.requests = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="distance" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
     *                   &lt;element name="dist" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                   &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="to" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "distance"
    })
    public static class Distances {

        protected List<Simulation.Distances.Distance> distance;

        /**
         * Gets the value of the distance property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the distance property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDistance().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Simulation.Distances.Distance }
         * 
         * 
         */
        public List<Simulation.Distances.Distance> getDistance() {
            if (distance == null) {
                distance = new ArrayList<Simulation.Distances.Distance>();
            }
            return this.distance;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice maxOccurs="unbounded" minOccurs="0">
         *         &lt;element name="dist" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="to" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "distOrFromOrTo"
        })
        public static class Distance {

            @XmlElementRefs({
                @XmlElementRef(name = "id", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "to", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "from", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "dist", type = JAXBElement.class, required = false)
            })
            protected List<JAXBElement<? extends Serializable>> distOrFromOrTo;

            /**
             * Gets the value of the distOrFromOrTo property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the distOrFromOrTo property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDistOrFromOrTo().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
             * 
             * 
             */
            public List<JAXBElement<? extends Serializable>> getDistOrFromOrTo() {
                if (distOrFromOrTo == null) {
                    distOrFromOrTo = new ArrayList<JAXBElement<? extends Serializable>>();
                }
                return this.distOrFromOrTo;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="location" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
     *                   &lt;element name="parkedCar" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                   &lt;element name="capacity" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                   &lt;element name="driverAvailable" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="position">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;choice maxOccurs="unbounded" minOccurs="0">
     *                             &lt;element name="x" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                             &lt;element name="y" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                           &lt;/choice>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "location"
    })
    public static class Locations {

        protected List<Simulation.Locations.Location> location;

        /**
         * Gets the value of the location property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the location property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLocation().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Simulation.Locations.Location }
         * 
         * 
         */
        public List<Simulation.Locations.Location> getLocation() {
            if (location == null) {
                location = new ArrayList<Simulation.Locations.Location>();
            }
            return this.location;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice maxOccurs="unbounded" minOccurs="0">
         *         &lt;element name="parkedCar" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="capacity" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="driverAvailable" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="position">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
         *                   &lt;element name="x" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *                   &lt;element name="y" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *                 &lt;/choice>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "parkedCarOrCapacityOrDriverAvailable"
        })
        public static class Location {

            @XmlElementRefs({
                @XmlElementRef(name = "capacity", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "id", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "type", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "parkedCar", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "driverAvailable", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "position", type = JAXBElement.class, required = false)
            })
            protected List<JAXBElement<?>> parkedCarOrCapacityOrDriverAvailable;

            /**
             * Gets the value of the parkedCarOrCapacityOrDriverAvailable property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the parkedCarOrCapacityOrDriverAvailable property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getParkedCarOrCapacityOrDriverAvailable().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
             * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
             * {@link JAXBElement }{@code <}{@link Simulation.Locations.Location.Position }{@code >}
             * 
             * 
             */
            public List<JAXBElement<?>> getParkedCarOrCapacityOrDriverAvailable() {
                if (parkedCarOrCapacityOrDriverAvailable == null) {
                    parkedCarOrCapacityOrDriverAvailable = new ArrayList<JAXBElement<?>>();
                }
                return this.parkedCarOrCapacityOrDriverAvailable;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;choice maxOccurs="unbounded" minOccurs="0">
             *         &lt;element name="x" type="{http://www.w3.org/2001/XMLSchema}integer"/>
             *         &lt;element name="y" type="{http://www.w3.org/2001/XMLSchema}integer"/>
             *       &lt;/choice>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "xOrY"
            })
            public static class Position {

                @XmlElementRefs({
                    @XmlElementRef(name = "x", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "y", type = JAXBElement.class, required = false)
                })
                protected List<JAXBElement<BigInteger>> xOrY;

                /**
                 * Gets the value of the xOrY property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the xOrY property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getXOrY().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
                 * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
                 * 
                 * 
                 */
                public List<JAXBElement<BigInteger>> getXOrY() {
                    if (xOrY == null) {
                        xOrY = new ArrayList<JAXBElement<BigInteger>>();
                    }
                    return this.xOrY;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="request" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
     *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="askTime" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                   &lt;element name="to" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="pickupTime" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                   &lt;element name="dropTime" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                   &lt;element name="deadlineTime" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                   &lt;element name="valid" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="optimized" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="delayed" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="relatedRequest">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="requestId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="carsNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "request"
    })
    public static class Requests {

        protected List<Simulation.Requests.Request> request;

        /**
         * Gets the value of the request property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the request property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRequest().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Simulation.Requests.Request }
         * 
         * 
         */
        public List<Simulation.Requests.Request> getRequest() {
            if (request == null) {
                request = new ArrayList<Simulation.Requests.Request>();
            }
            return this.request;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice maxOccurs="unbounded" minOccurs="0">
         *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="askTime" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="to" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="pickupTime" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="dropTime" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="deadlineTime" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="valid" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="optimized" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="delayed" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="relatedRequest">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="requestId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="carsNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "idOrTypeOrFrom"
        })
        public static class Request {

            @XmlElementRefs({
                @XmlElementRef(name = "type", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "delayed", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "from", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "relatedRequest", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "optimized", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "id", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "to", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "pickupTime", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "askTime", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "carsNumber", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "dropTime", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "valid", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "deadlineTime", type = JAXBElement.class, required = false)
            })
            protected List<JAXBElement<?>> idOrTypeOrFrom;

            /**
             * Gets the value of the idOrTypeOrFrom property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the idOrTypeOrFrom property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getIdOrTypeOrFrom().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
             * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link Simulation.Requests.Request.RelatedRequest }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
             * 
             * 
             */
            public List<JAXBElement<?>> getIdOrTypeOrFrom() {
                if (idOrTypeOrFrom == null) {
                    idOrTypeOrFrom = new ArrayList<JAXBElement<?>>();
                }
                return this.idOrTypeOrFrom;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="requestId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "requestId"
            })
            public static class RelatedRequest {

                @XmlElement(required = true)
                protected BigInteger requestId;

                /**
                 * Gets the value of the requestId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getRequestId() {
                    return requestId;
                }

                /**
                 * Sets the value of the requestId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setRequestId(BigInteger value) {
                    this.requestId = value;
                }

            }

        }

    }

}
